### ISSUE TITLE
Text encoding is not specified in responses

### ISSUE THREAD

**Issue by ticky** [Floofies/nubango#1]
The encoding of the responses is not specified, which means that the text is treated as ISO 8859-1 rather than Unicode.

This causes problems with stations which use Unicode characters in their names; the most obvious example is `€njoy 80's`, which happens to be the first item in the 80s Flashback section. It should have that Euro symbol at the start, but instead it comes through mangled like `â¬njoy 80's` in iTunes.

https://github.com/Floofies/nubango/blob/f80381f267fefe8d2167a459cb8671adde59c839/xml/80s-flashback.xml#L2

This behaviour should be fixed by updating this line of the CGI script:

https://github.com/Floofies/nubango/blob/f80381f267fefe8d2167a459cb8671adde59c839/cgi-bin/streamingRadioStations.sh#L48

to read:

```http
Content-Type: application/xml; charset=UTF-8
```

I don't currently have a Nubango server of my own set up to test this with, or I'd have pushed up a PR for this.

**Comment by Floofies** [comment]
Thanks for your diligence! In the preliminary investigation it seems that you are mostly correct. There are still some decoding issues. I think that maybe the XML files are also missing this line, and I will test it: `<?xml version="1.0" encoding="utf-8"?>`

**Comment by Floofies** [comment]
It looks like Apple's server uses this Content-Type: `Content-Type: text/xml; charset=ISO-8859-1`

**Comment by ticky** [comment]
> It looks like Apple's server uses this Content-Type: `Content-Type: text/xml; charset=ISO-8859-1`

Hmm, that seems strange, as the files Nubango contains *definitely* contain Unicode characters which can't be properly represented in ISO 9959-1. Does Apple's server also have the XML file specify an encoding which overrides this?

**Comment by Floofies** [comment]
Correct, the Apple server contradicts itself by including this at the top of its XML files: `<?xml version="1.0" encoding="utf-8"?>`

**Comment by Floofies** [comment]
After adding `charset=ISO-8859-1` to the header despite the fact that the XML is UTF-8, now I have gotten Google Chrome to reproduce the decoding bug, It now renders the euro symbol (and others) much like iTunes erroneously does. I think that the XML coming from the Apple server is indeed encoded as ISO-8859-1, despite the fact that the XML header says UTF-8. I also think that iTunes insists on decoding in ISO-8859-1 regardless of what is sent to it, so I will try re-encoding all the XML to see what happens.

**Comment by Floofies** [comment]
I am doing lots of experiments with encoding types to see how iTunes reacts. It seems that iTunes definitely uses the aforementioned encoding also known as ISO Latin 1, but converting our existing UTF8 text has proven difficult. I am not sure exactly how to proceed. A lot of characters found in Steve MacGuire's station list are not representable via ISO Latin 1. I have written a program which generates the unique alphabet present within a UTF8 string, and I processed all of the XML through it, compiling a list of characters which are present in the stations XML:

``` !"#&'(),-./0123456789:;<=>?@ABCDEFGHIJKLMNOPRSTUVWXY^_abcdefghijklmnopqrstuvwxyz|éö–’%QZ[ ßàäçèôúüŽ‘“„…€*+]ÖÜáãíóı™´Äêðñğœ¡”°É​—台四港第電香~ş\«»`{}ûÇÈ║″ÁÙâëîùąęłńśżΠήίαγδεηθικλμνορτφωύآأابةثجحخدرزسشصعغقلمنوىي♫ΒÎåčįİšųžАБВЕИКЛНПСЧабвгдежзийклмнопрстуфцчшья一三二五數普碼話通ÍÚïòõćđƯЈЗРЦЮхыэюҥằếệịọốộớừÀØæøě```

Clearly the problem is infeasible, as there are too many different localizations present in the character set. I can only assume that more modern versions of iTunes started to use UTF8 at some point. Considering that the target audience uses old versions of iTunes, I think that improving readability via custom substitutions (Rather than the illegible automatic substitutions) may be the best goal possible. For example, to start, by replacing the Euro with an "E".

Let me know if you have any additional comments... I would call this "encoding hell". This is a little disappointing.

**Comment by Floofies** [comment]
The proper encoding does look atrocious when re-encoded into ISO Latin 1 and fed that full character set. Here's a screenshot:

![Image Of Failure](https://user-images.githubusercontent.com/17753498/125218101-33f82300-e290-11eb-98c8-f40cc484b12e.png)

**Comment by ticky** [comment]
Oh, is the XML here generated from a source that isn't the original station list? That might explain why Unicode data is in there when it shouldn't be!

It's a shame, but yeah, it seems like the best approach we have is to replace any non-Latin 1 characters with Latin 1.

---

Converting that repertoire you've presented using `iconv`, with any characters not supported in ISO 8859-1 replaced with `?`, and then back to Unicode, I can see that this subset is supported:

```bash
$ echo "!"#&'(),-./0123456789:;<=>?@ABCDEFGHIJKLMNOPRSTUVWXY^_abcdefghijklmnopqrstuvwxyz|éö–’%QZ[�� ßàäçèôúüŽ‘“„…€*+]ÖÜáãíóı™´Äêðñğœ¡”°É​—台四港第電香~ş\«»\`{}ûÇÈ║″ÁÙâëîùąęłńśżΠήίαγδεηθικλμνορτφωύآأابةثجحخدرزسشصعغقلمنوىي♫ΒÎåčįİšųžАБВЕИКЛНПСЧабвгдежзийклмнопрстуфцчшья一三二五數普碼話通ÍÚïòõćđƯЈЗРЦЮхыэюҥằếệịọốộớừÀØæøě" | iconv -t ISO8859-1 --unicode-subst=\? | iconv -f ISO8859-1
#&'(),-./0123456789:;<=>?@ABCDEFGHIJKLMNOPRSTUVWXY^_abcdefghijklmnopqrstuvwxyz|éö??%QZ[?? ßàäçèôúü??????*+]ÖÜáãíó??´Äêðñ??¡?°É—???????~?\«»`{}ûÇÈ??ÁÙâëîù????????????????????????????????????????????????????Îå????????????????????????????????????????????????????ÍÚïòõ??????????????????????ÀØæø?
```

So these characters are fine to leave as-is:

```
#&'(),-./0123456789:;<=>?@ABCDEFGHIJKLMNOPRSTUVWXY^_abcdefghijklmnopqrstuvwxyz|éö%QZ[ ßàäçèôúü*+]ÖÜáãíó´Äêðñ¡°É—~\«»`{}ûÇÈÁÙâëîùÎåÍÚïòõÀØæø
```

And these would need replacement:

```
–’��Ž‘“„…€ı™ğœ”台四港第電香ş\║″ąęłńśżΠήίαγδεηθικλμνορτφωύآأابةثجحخدرزسشصعغقلمنوىي♫ΒčįİšųžАБВЕИКЛНПСЧабвгдежзийклмнопрстуфцчшья一三二五數普碼話通ćđƯЈЗРЦЮхыэюҥằếệịọốộớừě
```

**Comment by Floofies** [comment]
`iconv` has a couple of options that may help: `//TRANSLIT` and `//IGNORE` which, when combined, causes `iconv` to transliterate similar characters and delete everything else. I happen to have written a script which imports `iconv` and does this transliteration. After some additional testing I will see how far that gets us!

**Comment by ticky** [comment]
Oh that's super helpful, I didn't realise `iconv` could do that itself!

**Comment by Floofies** [comment]
I have pushed commit 61612139fbfab8dffb8f68568f1ca40afae0f2fc which seems to eliminate any un-representable characters, providing a standard ISO-8859-1 format for all of the XML files, and a refined encoder

**Comment by Floofies** [comment]
I have pushed commit 61612139fbfab8dffb8f68568f1ca40afae0f2fc which seems to eliminate any un-representable characters, providing a standard ISO-8859-1 format for all of the XML files, and a refined encoder
